import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

import csv
import requests
from core.auth import get_access_token

def parse_csv(filepath: str) -> list:
    """
    Parses the Autopilot CSV file generated by Get-WindowsAutopilotInfo.
    Handles UTF-16 encoding (default PowerShell output) and UTF-8.
    """
    devices = []
    for encoding in ("utf-16", "utf-8-sig", "utf-8"):
        try:
            with open(filepath, encoding=encoding) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    devices.append({
                        "serialNumber":       row.get("Device Serial Number", "").strip(),
                        "productKey":         row.get("Windows Product ID", "").strip() or "",
                        "hardwareIdentifier": row.get("Hardware Hash", "").strip(),
                    })
            if devices:
                return devices
        except Exception:
            continue
    return devices

def upload_autopilot_device():
    """
    Uploads a device to Windows Autopilot via Microsoft Graph API.
    Uses importedWindowsAutopilotDeviceIdentities endpoint (correct for POST).
    """
    print("\n=== Microsoft Graph: Upload Device to Autopilot ===")

    csv_path = input("Enter path to autopilot CSV file: ").strip().strip('"')
    if not os.path.exists(csv_path):
        print(f"❌ File not found: {csv_path}")
        return

    group_tag = input("Enter Group Tag (optional, press Enter to skip): ").strip()

    devices = parse_csv(csv_path)
    if not devices:
        print("❌ Could not parse CSV file. Check the file format.")
        return

    print(f"\nFound {len(devices)} device(s) in CSV:")
    for i, d in enumerate(devices, start=1):
        print(f"  {i}. Serial: {d['serialNumber']}  Hash length: {len(d['hardwareIdentifier'])} chars")

    confirm = input(f"\nUpload {len(devices)} device(s) to Autopilot? [y/N]: ").strip().lower()
    if confirm != "y":
        print("Cancelled.")
        return

    token = get_access_token()
    if not token:
        print("❌ Error: Could not obtain an access token.")
        return

    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type":  "application/json"
    }

    success = 0
    for device in devices:
        payload = {
            "@odata.type":        "#microsoft.graph.importedWindowsAutopilotDeviceIdentity",
            "serialNumber":        device["serialNumber"],
            "hardwareIdentifier":  device["hardwareIdentifier"],
            "state": {
                "@odata.type": "#microsoft.graph.importedWindowsAutopilotDeviceIdentityState",
                "deviceImportStatus":    "pending",
                "deviceRegistrationId":  "",
                "deviceErrorCode":       0,
                "deviceErrorName":       ""
            }
        }
        if device["productKey"]:
            payload["productKey"] = device["productKey"]
        if group_tag:
            payload["groupTag"] = group_tag

        # Correct endpoint for uploading devices
        url = "https://graph.microsoft.com/beta/deviceManagement/importedWindowsAutopilotDeviceIdentities"
        response = requests.post(url, json=payload, headers=headers)

        if response.status_code in (200, 201):
            data = response.json()
            print(f"\n✅ Uploaded: {device['serialNumber']}")
            print(f"   Import ID: {data.get('id')}")
            print(f"   Status:    {data.get('state', {}).get('deviceImportStatus', 'N/A')}")
            success += 1
        elif response.status_code == 409:
            print(f"\n⚠️  Already registered: {device['serialNumber']}")
        else:
            print(f"\n❌ Failed for {device['serialNumber']} (HTTP {response.status_code}):")
            print(response.text)

    print(f"\n--- Summary ---")
    print(f"Uploaded: {success} / {len(devices)}")
    if success > 0:
        print(f"\nℹ️  Run sync_autopilot.py to trigger an immediate sync.")
        print(f"Device may take 5-15 minutes to appear in Intune portal.")

if __name__ == "__main__":
    try:
        upload_autopilot_device()
    except Exception as e:
        print(f"Critical error: {e}")
